### ISSUE TITLE
keypresses will not get seen in APEX 20.1

### ISSUE THREAD

**Issue by m-cas** [grlicaa/D3CollapsibleTreeChart#3]
I've defined a new event in the plugin code: keydown. It works fine up to APEX 19 just by adding 
`    nodeEnter.on("keydown", function(d) {
      fireApexEvent("keydown", d);
    });
`
Alas the code stops recording the keypress event on Firefox and Safari (works on Chrome) from APEX 20.1 unless this new line is added:

`    var nodeEnter = node.enter()
      ...
      .attr("tabindex", "1")  // this line is new
     ... `

best Massimo

**Comment by grlicaa** [comment]
Fixed in 6.0.2 thank you @m-cas  for catching this one.
